#
# Alacritty config
#
# Adapted from https://github.com/smallwat3r/dotfiles/blob/255758cf98f8d5b8b625665421c390ba14db6c38/alacritty/alacritty.yml
#

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 140
    lines: 50

  padding:
    x: 10
    y: 10

  dynamic_padding: true
  decorations: none
  startup_mode: Windowed

scrolling:
  history: 10000
  multiplier: 3
  scrolling_multiplier: 3

font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic

  size: 11.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'

colors:
  primary:
    background: '0xfafafa'
    foreground: '0x383a42'

  normal:
    black: '0x383a42'
    red: '0xe45649'
    green: '0x50a14f'
    yellow: '0xc18401'
    blue: '0x0184bc'
    magenta: '0xa626a4'
    cyan: '0x0997b3'
    white: '0xfafafa'

  bright:
    black: '0x383a42'
    red: '0xe45649'
    green: '0x50a14f'
    yellow: '0xc18401'
    blue: '0x0184bc'
    magenta: '0xa626a4'
    cyan: '0x0997b3'
    white: '0xfafafa'

background_opacity: 1

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

  url:
    modifiers: None

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true
enable_experimental_conpty_backend: false

alt_send_esc: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false

key_bindings:
  - { key: Key0,   mods: Command,         action: ResetFontSize    }
  - { key: Equals, mods: Command,         action: IncreaseFontSize }
  - { key: Add,    mods: Command,         action: IncreaseFontSize }
  - { key: Minus,  mods: Command,         action: DecreaseFontSize }
    # Fix weird hash key bug not working on MacOS
  - { key: Key3,   mods: Alt,     chars: "\x23"                    }
  - { key: PageUp,                        action: ScrollPageUp     }
  - { key: PageDown,                      action: ScrollPageDown   }
